when:
 - event: push
   branch: develop

steps:
  - name: build
    image: docker:cli
    commands:
      - pwd
      - ls -la
      - ls -la bash-pipelines-helpers/
      - ./bash-pipelines-helpers/build-image-dev.sh
  - name: release
    image: docker:cli
    commands:
      - ./bash-pipelines-helpers/release-image.sh